# Generated by Django 5.1.6 on 2025-08-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='extract_data',
        ),
    ]
